services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    ports:
      - '6379:6379'

  mongoDB:
    image: mongo:8
    ports:
      - '27017:27017'

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mongoDB

volumes:
  postgres_data:
