"""fix_unique_constraint

Revision ID: a940ec81cf48
Revises: 749c11bd4181
Create Date: 2026-05-16 16:41:05.805488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a940ec81cf48'
down_revision: Union[str, Sequence[str], None] = '749c11bd4181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
